# Port to run on
server:
  port: ${port:8080}

# Our log file path and name
logging:
  file: logs/erc20-rest-service.log

# Endpoint of an Ethereum or Quorum node we wish to use.
# To use IPC simply provide a file path to the socket, such as /path/to/geth.ipc
nodeEndpoint: http://localhost:8081

# The Ethereum or Quorum address we wish to use when transacting.
# Note - this address must be already unlocked in the client
fromAddress: "0xf6de496ec5601d74937ddd77af09c8cd4ba41ab5"

# Our token contract address
contractAddress: "0x091e99d1fbf1d18b7c42aeb6938dec588b2aae9c"

# passphrase to encrypt key files
encryptPassphrase: "password"