spring:
  profiles:
    active: dev
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    hibernate:
      show-sql: true
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
