spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/wallet?autoReconnect=true&useSSL=false
    username: contentbox
    password: ThePassw0rd

contentbox:
  fullnode:
    # Endpoint of an Ethereum or Quorum node we wish to use.
    # To use IPC simply provide a file path to the socket, such as /path/to/geth.ipc
    nodeEndpoint: http://localhost:8545
    # The Ethereum or Quorum ethAddress we wish to use when transacting.
    # Note - this ethAddress must be already unlocked in the client
    fromAddress: "0xf6de496ec5601d74937ddd77af09c8cd4ba41ab5"
  wallet:
    # passphrase to encrypt wallet files
    passphrase: "password"
    dir: "/User/frankdai/wallet_files"
    api:
      allowedPubkey: "BAK2uyd5XgVlj3JB0jA00dyPm4j7EOj4SLtN1LN9RCWc4uuemwjr22M2OQUOMqP4dSSL4h9iOu0jtmQDlk00bkI="
  # We use AES 256 to encrypt private keys
  aes256:
    password: 25fd9747c488b18a1d60723a4e311c0f200059f65c4d25a3079239c29a635d5a2406ece916aab23a # mypassw0rd
    salt: 1419efe5525bd69abd8bdca8af8fb0fa74a08002adfc21fb0d4bb78b18ae8885e8950bf3c13f4b87 # mysalt
